  main = ".open-next/worker.js"
  name = "whisper-func"
  compatibility_date = "2025-03-25"
  compatibility_flags = ["nodejs_compat"]
  [assets]
  directory = ".open-next/assets"
  binding = "ASSETS"

# 单个路由配置
route = { pattern = "whisper.obli.uno/*", zone_name = "obli.uno" }